development: &default
  city_name: 'Austin'
  state_name: 'Texas'
  country_name: 'United States'
  site_name: 'SXSW Civic Hackathon'
  daily_vote_limit: 100

test: &test
  <<: *default

production: 
  <<: *default
  
cucumber:
  <<: *test