development: &default
  city_name: 'Austin'
  state_name: 'Texas'
  country_name: 'United States'
  site_name: 'SXSW Civic Hackathon'
  daily_vote_limit: 100
  points: 
    vote_on_issue: 1
    submit_an_issue: 5
    tweet_clickthrough: 1
    report_closed_one_week: 5 
  
  awards: 

test: &test
  <<: *default

production: 
  <<: *default
  
cucumber:
  <<: *test